### ISSUE TITLE
Copyright statements missing in footer

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1075]
All copyright statements on publisher pages are missing from the footer. This may be related to a Hyrax upgrade or moving to create Publishers via a form.

In past views, the copyright statement was there by default, dynamically dropping in the Publisher name.

**Comment by conorom** [comment]
When the simple_form updates the publisher rows, empty text boxes are set to blank where they would have been NULL previously. This includes `footer_block_c` and highlights the importance of using `.present?` and `.blank?` for checks. Allowing the user to send blank values is usually desirable so that they can wipe out previously-entered text. I had already added a `.present?` to the `footer_block_a` check to get the default logo working, but missed this problem.

In order to get the default (copyright symbol) behavior back before the next code release I set the `footer_block_c` values in production back to NULL.
