### ISSUE TITLE
Redirect orphaned assets URL to the existing asset

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#1080]
- [ ] Investigate if we can do this. (This is a NOID on production. IF parent is blank, check is entry if fileset goes here, if not goes here - a static page - something like that.)
- [x] Do this. (conorom: see note at end, the redirection doesn't care about the FileSet being orphaned or not)
- [ ] If we can't do this, then pull A&E in.

**Comment by conorom** [comment]
blocked by #1108

**Comment by conorom** [comment]
Actually it's not completely blocked. The scenario of an orphaned asset whose redirect field has not been populated should also be handled. Right now loading the page for an orphaned asset gives an error 500 because of several references to the monograph's title etc. So... what to do about that? if `parent.blank?` bump to static/not allowed page. Or else change the references that break the page to handle the lack of parent.

**Comment by conorom** [comment]
The `redirect_to`field is created. Once this ticket is done, with a test of redirection behaviors in place, it should be removed from the FileSet info view (`_attribute_rows_info.html.erb`) and `expect(page).to have_content`removed from `edit_file_set_spec.rb`

**Comment by conorom** [comment]
In the spirit of K.I.S.S., it doesn't matter whether the FileSet has no parent or not, a valid FileSet ID in `redirect_to` will take you to the other FileSet regardless.
Also I don't see the harm in leaving `redirect_to` showing for now, seeing as you're going to get bounced from that page anyway.
