### ISSUE TITLE
Safari 10: Double captions in video player

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1234]
In Safari 10.1 and 9.1, when I play video embedded in an EPUB or on an asset page and it has captions, two sets of captions appear in the video player. Depending on how the player is styled, sometimes captions can be layered over top each other.

Embedded player:
![bs_macelc_safari_9 1 4](https://user-images.githubusercontent.com/1686111/30663441-a22eb7fa-9e18-11e7-9bce-13a05acb1c71.jpg)

Asset page player:
![bs_macsie_safari_10 1 1](https://user-images.githubusercontent.com/1686111/30664023-611e2eb0-9e1a-11e7-9d9b-09b4d8bff2cb.jpg)

- [ ] investigate Safari's use of a transcript files in HTML5 `video`
- [ ] is this already a bug that has been identified in AblePlayer or something with our implementation? 
- [ ] remove Safari's default captions so only AblePlayer's implementation of captions is displayed

**Comment by conorom** [comment]
Possibly relevant:
https://support.apple.com/en-us/HT202797

**Comment by jmcglone** [comment]
Oddly, this only happens on the NYU assets with captions. It does not appear on the Michigan captioned videos:

![screen shot 2017-11-06 at 4 51 22 pm](https://user-images.githubusercontent.com/1686111/32468200-ec1f18b8-c312-11e7-8699-9aa2dc8d5a49.png)

Perhaps it has to do with the WebVTT file and how it was formatted?

**Comment by conorom** [comment]
In Safari 11 I see the problem in both nyupress and michigan videos. I can get rid of it by unchecking the "Prefer closed captions and SDH" checkbox in macOS settings (see link above).
However the behavior is inconsistent. When you uncheck the box while the video is playing, it gets rid of the "native text track" every time. However this setting doesn't seem to persist next time round, either reloading the page or restarting Safari brings back the problem.

I assume that this checkbox being checked makes Safari default to turning on the native text track using the src from <track kind="captions" ... >, if such a track is there (this would be the accessible one, as opposed to <track kind="subtitles" ... >, say). Almost as if it had the default attribute set (see links below).

Because Able Player treats captions and subtitles exactly the same, one solution that seems to work is to simply mark the track as a subtitle, thus Safari never feels the need to muscle in to "let me make that accessible for you without you touching a control". You could argue that this misrepresents the track, if it has descriptions of sound effects etc. I fear the alternative would be even worse though as we would have to substantially hack Able Player (perhaps even using a custom "kind" attribute Safari won't pick up). Or we'd have to stop using Able Player for Safari, or at all.


http://ableplayer.github.io/ableplayer/demos/video2.html
https://github.com/ableplayer/ableplayer/issues/5
https://github.com/videojs/video.js/issues/1054
https://github.com/videojs/video.js/blob/master/docs/guides/text-tracks.md
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track
https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video
