### ISSUE TITLE
Scroll wheels for zoom in/out and accessibility

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1302]
Are scroll wheels an accessibility concern for zooming in and out? Should we disable them for zooming on leaflet and for users to click the + / - buttons in order to zoom?

- [x] Investigate the validity of this concern and, 
- [ ] remove the scroll wheel functionality for zooming

**Comment by mbakeryo** [comment]
Related to Bug #1126

**Comment by sethaj** [comment]
This will relate to #1126

**Comment by jmcglone** [comment]
http://cliffcloud.github.io/Leaflet.Sleep/

**Comment by conorom** [comment]
After poking around with Leaflet.Sleep it doesn't seem to have any provision to wake the map with tab navigation. So the only way to use it, given our focus on accessibility, is to not have a sleep message or sleep opacity on the map. Therefore keyboard users are basically using the map while it is "asleep". This might all work OK. I'll give it a quick go and if it's no good then the time has definitely come to remove scroll-to-zoom from Leaflet.

**Comment by conorom** [comment]
For now the decision is to turn off scrollwheel zoom. There are comments in #1126 also relating to this. To sum up:
- Leaflet.Sleep is awesome but we'd need to either run it with the sleep message & map opacity off (tried it, it's a little confusing) or add "wake events" to Leaflet.Sleep itself to remove the message/opacity when a keyboard user focused on the map (or any related element).
- Having gone to the trouble of adding these wake events, we'd have put ourselves in the situation of forcing the user to wake the map to take in the image. This seems like a step backwards, especially when we went to a lot of effort to have the image "best fit zoom" to the map on page load so that the user wouldn't have to touch the map/controls to look at the entire image in the largest size possible.
- none of the above sounds like it is worth the maintenance overhead of hacking another Leaflet add-on
