### ISSUE TITLE
acessibility contrast issues

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1330]
Some fairly minor contrast issues picked up by aXe:

1) Breadcrumbs: The page the breadcrumb is on (so for "Home / Monograph Name / Asset Name" this would be Asset Name) needs more contrast.

2) The X to close out the survey needs more contrast. I'm pretty sure this is a bootstrap 'alert' style. And I'd imagine that it's not just for alert-info but maybe also for the other alerts. I guess we'll need to override bootstrap here.

3) aXe is reporting that for Indiana, the "Powered by Fulcrum" footer with Contact, Contribute, Log Out, etc don't have sufficent contrast.

**Comment by moseshll** [comment]
#1 and #2 are thus far straightforward, but #3 is problematic: WAVE gripes about small text contrast even when the text color is set to #FFFFFF. This suggests a need to rethink Indiana's branding choices for background elements. I will bring this up as a stand-up issue because it's sounding like more than a simple tweak.
