### ISSUE TITLE
Investigation: Support for citation managers

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#138]
Expose metadata in format compatible with citation management software such as Zotero and RefWorks.

Look at DLXS and Deep Blue Data (Sufia).

**Comment by sethaj** [comment]
Google Scholar wants `<meta>` tags:
https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

Here's how Sufia does it:
https://github.com/projecthydra/sufia/blob/master/app/views/shared/_citations.html.erb#L17

Zotero wants `<meta>` tags or CoiNS
https://www.zotero.org/support/dev/exposing_metadata

Here's how Sufia does it:
https://github.com/projecthydra/sufia/blob/master/app/helpers/sufia/citations_behaviors/formatters/open_url_formatter.rb


It looks like RefWorks wants CoiNS. And a special export button? RefWorks could be complicated since it's a paid service and integration might be difficult. Do we really want it? Sufia doesn't seem to support it.

**Comment by sethaj** [comment]
#674 is for google scholar implementation

**Comment by sethaj** [comment]
#679 is the Zotero implementation
