### ISSUE TITLE
Review MSU-UARC screener survey

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1503]
Review screener survey created by MSU-UARC and provide feedback as necessary.

https://msu.co1.qualtrics.com/jfe/preview/SV_4ZvwXjAUwcar9C5?Q_CHL=preview

**Comment by jgmorse** [comment]
Compiling feedback here so we can coordinate a response:

> electronic scholarly resources
This seems like a perfectly adequate generic description of the Fulcrum that's being tested.


> How often do you search for and look at online academic journal articles or scholarly books?
Surely we don't need this level of detail in the responses?  Remove "Once every two weeks" and "Once every two months" at the least.

Otherwise, it looks good to me.

**Comment by mbakeryo** [comment]
I agree with @jgmorse's suggestion re: frequency of searching for articles/scholarly books. The rest of the survey looks fine to me, including the generic description.

**Comment by jmcglone** [comment]
Ok, Thanks! I agree with your assessments and don't have much more to add to them. I'll send on a response to Sarah with the changes for "how often" and that we think the generic description of Fulcrum works just fine.
