### ISSUE TITLE
Collect feedback from Gabii Team

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1562]
Share the preview version of Gabii with EPUB (from Apex), WebGL, assets, links to database, and aboutware, and branding for review.

Based on feedback from Gabii team, iterate and create new tickets as needed.

**Comment by jmcglone** [comment]
When should we make this due?

**Comment by mbakeryo** [comment]
Let's try for 3/19 (if we can get it out to the Gabii team by 3/16).

**Comment by mbakeryo** [comment]
Questions for the Gabii team when preview request goes out:

Tables: Rachel requested that the tables be made available as .csv files instead of Excel. There are 2 tables that when converted to .csv files they were completely changed, meaning the numbers are no longer the same as what was shown in the Excel file. For these files, could you please provide the correct and final .csv file? [These tables can be found in this Google folder - Content. Please note that the Excel and .csv files have been provided so that you can see the difference.]

Tables: When the Excel files were converted to .csv, the heading and column formatting was lost. Can you please make any adjustments to the formatting and send the final .csv file(s)? If you are fine with the files as is, let us know. [These tables can be found in this Google folder - Formatting.]

Assets and Metadata: Please review all of the assets in the Media tab. Please confirm that all of the assets you wish to be included are displaying *and* that all metadata for the assets is accurate. [Please note that there is an asset for all of the tables as a zipped file. Please confirm that the metadata is as you wish.]

**Comment by jmcglone** [comment]
Sent to preview on 3/19
