### ISSUE TITLE
[BUG] Errors when creating Institutions

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1670]
- [x] Clicking `Institutions` in the Fulcrum dashboard generates a 500.  (This only happens after creating at least one Institution.)
- [ ] While creating an Institution, there's no way to authorize it to a Product.

**Comment by gkostin1966** [comment]
The institution record is metadata for the institution key.  Create a lessee record with the institution key in order to associate the institution with a product.  A lessee record represents any leasing entity: user, institution, application, etc.  This level of indirection keeps the lessees table clean while supporting multiple lessee types.  Not sure if this level of indirection is desirable but is how the system currently works for this sprint.
