### ISSUE TITLE
UI Updates for Gabii database

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#1673]
- [x] The "Problems/comments?" opens a form for submitting feedback. On Submit, it currently sends email to dlps-help@umich.edu. It should instead use the value of the `contactlink` field in Collmgr.
- [x] Remove BETA from banner logo.
- [x] Change footer link "A component of the online..." to use the DOI.
- [x] Add authors to record citation in Share/Cite popup.

**Comment by jgmorse** [comment]
Created /quod-dev/cgi/f/feedback/fb/fb_gabii_1_data.pm to use the `mpub-help@umich.edu` and confirmed that the code is being called, but not seeing the ticket show up in Service Desk... maybe there's code that doesn't actually send the email (or sends to Roger) if we're in preview?

**Comment by respinos** [comment]
feedback was changed recently to send to the contact email address; I'll take a look.

**Comment by respinos** [comment]
`feedback` was looking for a collid pattern only made up of letters and numbers; I modified it to accept `_` (e.g `gabii_1_data`). Can you try now?

**Comment by moseshll** [comment]
@jgmorse @respinos `/quod-dev/cgi/f/feedback/fb/fb_gabii_1_data.pm` contained the e-mail address `mpbub-help@umich.edu` instead of `mpub-help@umich.edu`. I corrected it to the latter. I assume this file needs to be under revision control at some point. Can I test the feedback mechanism safely without spamming (someone)?

**Comment by jgmorse** [comment]
Looks great @moseshll , please do release to production.

**Comment by moseshll** [comment]
Released.
