### ISSUE TITLE
Clear flash messages after cosign login

### ISSUE THREAD

**Issue by conorom** [mlibrary/heliotrope#1688]
- [x] copy UMRDR's code to clear flash messages after cosign login
- [x] test that below way to get a flash message no longer occurs

It's pretty easy to get a bogus "You are not authorized to access this page" flash message when logging in for the first time.

Here is one easily-reproducible way:
- make sure you have no incognito windows open
- copy a direct link to the Gabii monograph on any of the production-mode apps
- open a new incognito window
- paste the URL and go
- complete the cosign login and two-factor auth
- you will be on the monograph page with a bogus flash message visible

**Comment by gkostin1966** [comment]
I the code from UMRDR was replaced some time ago and it appears to have cleared the flash message on successful login.

The flash message still appears if the user clicks the browser back button to avoid the cosign login.  

I spent some time poking around the Devise and Warden code looking for a place to clear the flash message prior to displaying the cosign login page without success.

I did find this https://joanswork.com/devise-turn-off-select-flash-messages/ which is a nice trick to know but apparently the "You are not authorized to access this page." isn't in the devise.en.yml file.  My guess the message is hardcoded in Hyrax because I didn't find the message in any *.en.yml file under heliotrope.

I found this https://www.reddit.com/r/rails/comments/5xbubd/help_with_devise_strategies_and_flash_messages/ which modifies the Warden::Strategies::Base fail method to add more messages but this won't work in removing messages.

I found this https://makandracards.com/makandra/1174-why-a-rails-flash-message-is-shown-twice which is good to know, but again, not useful here.

Going to call it done for now and move on to something else unless it is determined that back button edge case needs to be solved.
