### ISSUE TITLE
FactoryService Cache Fail

### ISSUE THREAD

**Issue by gkostin1966** [mlibrary/heliotrope#1692]
./app/services/factory_service.rb works in theory but fails in practice.

- [x] Revisit the purpose of the FactoryService
- [x] Redesign the FactoryService cache
- [x] Implement the redesign
- [x] Test the redesign
- [x] Repeat Until Success
- [x] consider caching EPUBs and WebGL at the end of the import process. In many ways unpacking them for display in the app is analogous to derivative creation. Also, triggering this from a user action is dodgy and causes issues, especially when one unpacked item is reliant on another.

**Comment by conorom** [comment]
Added point about unpacking at ingest time not on user action

**Comment by conorom** [comment]
Confirming that after importing 13 EPUBs for HOB only about half would get unpacked and loaded on first browser load. Took one or two page reloads to get the EPUB to display. This will be more of an issue when we import 1000s of EPUBs and it won't be one of us triggering the caching for the first time. The EPUB will just look broken to somebody.

**Comment by sethaj** [comment]
I think we'll probably have to unpack them at "featured representative setting time" rather than ingest. Well for new things. For replacement, we'll need to do it at ingest since it's already an "epub" or "webgl" featured rep.

**Comment by sethaj** [comment]
I think then, that we've decided on this (right?):

1) "Cached" content (epub, webgl) will be considered derivatives ala Hyrax. "Caching" a file had meant just pulling it out of Fedora and putting it on the file system.
We'll keep doing that, but now we'll put them where hyrax puts derivatives `./tmp/derivatives/<pair-tree>`. We're going to call this "unpacking" or an "unpacked" epub/webgl/file and not "caching/cached" from now on.

2) When a FileSet's FeaturedRepresentative is set (epub or webgl), the unpacked file will be created. We do this now and not during ingest because the ingestion process doesn't know the file is a epub/webgl. A user needs to do that (currently).

3) When a FileSet with a FeaturedRepresentative of "epub" or "webgl" is updated ("reversioned" with a new epub/webgl) the new file is unpacked (the old removed first).

But there's a lot of interdependant code right now and it's a little confusing. So to accomplish this, we're going to try to develop in smallish PRs with new code exisiting in parallel to the old code. Once the new code is in place, we'll "convert" all the epubs/webgls to the new "unpacked" model using a rake task. If the new "unpacking" code path works for everyone, we'll start removing the old code and eventually the old "cached" content.

Part 1
- [ ] Create an UnpackJob that unpacks an epub into it's derivatives space. It should also create the sqllite database for search.
- [ ] The UnpackJob should also unpack webgls into it's derivatives space.
- [ ] The UnpackJob should create the epub-webgl mapping when it needs to.

Part 2
- [ ] The UnpackJob should be called when a FileSet's FeaturedRepresentatives is "set" (epub, webgl only)
- [ ] The UnpackJob should be called when a FileSet (that's already a FeaturedRepersentative of epub, webgl) is "reversioned"

Part 3
- [ ] Create and run a rake task that will unpack all exisiting epub/webgls
- [ ] Front-end views should use the new "unpack" code path

Part 4
- [ ] Does this all work and make sense? Are the problems like race conditions that we need worry about (and use something like redlock to solve maybe?)
- [ ] Replace and remove all old code.
- [ ] Remove old "cached" data.

**Comment by sethaj** [comment]
Close #1571 when this is all done
