### ISSUE TITLE
Monograph catalog displays two permalinks

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#1696]
If the handle field is populated in the monograph metadata record, it will display citable links on the monograph catalog page.

![screen shot 2018-03-29 at 4 43 39 pm](https://user-images.githubusercontent.com/1686111/38112717-cf6887bc-3370-11e8-8ae1-445a43e7858e.png)

If I have a DOI for a monograph, I want that to display there, not the generic handle.

**Comment by conorom** [comment]
The problem here was that the `hdl` field is treated as a NOID, in the event you don't want the given object's id to be the value used in the `handle.net` URL. This is the field/logic I copied over from FileSets when adding citable links to Monographs. I wrote a comment at the time the DOIs probably wouldn't be needed for Monographs. Dunno why.

I've made #1717 to discuss how we're thinking about and planning to use these fields (why they exist, even) and boil down how they can best be described for editors (and ourselves).

aside: About half of FileSets in production needlessly have `hdl` populated.
