### ISSUE TITLE
Report Characterization errors

### ISSUE THREAD

**Issue by sethaj** [mlibrary/heliotrope#1701]
Occasionally when ingesting new files fits characterization will not produce height/width dimensions for images.

RIIIF needs height/width info in solr to be able to display images, so these FileSet pages seem broken.

In these cases however, characterization doesn't seem to outright fail and be reported in resque, they just aren't right.

Since we need height/width for all images, we need a way to report back to the user/uploader that there was a problem.

Maybe this is triggering a characterization failure (although if the CharacterizeJob fails, then the DerivativeJob will never be called), or maybe something else. But right now the error is just never reported.

**Comment by sethaj** [comment]
Example files that fail characterization in this way are gabii's Figure3_more.jpg and Figure4_more.jpg

**Comment by conorom** [comment]
If it's too much hassle to deal with as part of ingest, we could resort to a cron job based on a task based on the console command that checks for blank width/height. If this was running in preview, we'd catch dodgy images before they got to production, as long as the systems were truly identical (FITS version and config).

Otherwise I guess we add a custom "simple" job that goes right at the end of the ingest sequence to flag the problem.
