### ISSUE TITLE
Edit metadata for an asset (file) attached to multiple sections within a monograph

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#204]
**STORY**
As an editor, I would like the system to inform me when I'm editing an an asset or its metadata that is included in multiple sections of the same monograph, so that I know whether or not I need to make my changes in multiple places and so I don't make inadvertent changes to other sections.

**ACCEPTANCE**
- [ ] Only the current asset is changed by the edit being saved.
- [ ] The system should prompt me to let me know when I am editing an asset that is attached in multiple sections.  It should have a warning message that the changes won't be applied to the other clones, so I need to go edit them manually if I want the changes to apply to more than one clone.
- [ ] The system should show me which other sections the asset is attached to (e.g. Links to the other clones)
- [ ] All these acceptance criteria apply whether I'm editing metadata or file content for the asset.
- [ ] ~~The system should prompt if I want to edit just the copy on this section (i.e. clone it and make changes only to the clone associated with this section)~~  - This will be future work.

**Comment by shanitajohn** [comment]
**Questions**
Once the user has created an asset that is attached to 2 sections, what happens when the user edits the description field (or other metadata fields)?

  -[ ] The user should be notified there are other clones of the asset
  -[ ] Only the current clone is changed by the edit being saved
  -[ ] There is a pointer to the other clone(s) of the asset
  -[ ] The user is prompted that they will need to make the same changes to other clones (near term solution)
  -[ ] The user is prompted if they want to apply the same changes to the other clones (hold for later)

**Comment by mark-dce** [comment]
Related tickets for context
#202 Attach the same file to multiple sections in a template (via importer)
#203 Attach the same file to multiple sections from the UI
#204 Edit metadata for a file that's attached to multiple sections
#205 Delete a file that's attached to multiple sections

**Comment by conorom** [comment]
Now that a FileSet's section(s) are simply stored as a multi-valued field (section_title) there is no issue with editing the metadata of a FileSet attached to multiple sections. No "clone" relationship exists, nor any decision on transferring the edits to clones. You can't have different metadata for the same FileSet as it appears in one section versus another. If that is required (and it's quite the opposite of what is required right now), the FileSet should be duplicated.
