### ISSUE TITLE
Delete an asset (file) attached to multiple sections within a monograph

### ISSUE THREAD

**Issue by mark-dce** [mlibrary/heliotrope#205]
**STORY**
As an editor, I would like the system to inform me when I'm deleting an an asset that is included in multiple sections of the same monograph, so that I don't make inadvertent changes to other sections.

**ACCEPTANCE**
- [ ] Only the current asset is deleted by the action.  (Other clones will not be deleted).
- [ ] The system should prompt me to let me know when I am deleting an asset that is attached in multiple sections.  It should warn me that only the current asset will be deleted, and if I want to delete the other clones, I will have to manually delete them all.
- [ ] I should be able to easily find other clones in case I want to delete them too. (e.g. Links to the related assets)
- [ ] If there is a "related asset" relationship on the other clones, other clones need to be updated to no longer refer to the deleted clone.  (i.e. If I visit the show page for an asset, and it has a list of related assets/clones, the asset that I just deleted should no longer appear in the list)

**Comment by shanitajohn** [comment]
**QUESTIONS**

Once the user has created an asset that is attached to 2 sections, what happens when the user deletes the asset?
- [ ] The user should be notified there are other clones of the asset
- [ ] There is a pointer to the other clone(s) of the asset
- [ ] Only the current clone is deleted by the action
- [ ] The user is prompted that they will need to manually delete the other clones (near term solution)
- [ ] The user is prompted if they want to delete all the other clones **(hold for later)**
- [ ] Other clones need to be updated to no longer refer to the deleted clone

**Comment by mark-dce** [comment]
Related tickets for context
#202 Attach the same file to multiple sections in a template (via importer)
#203 Attach the same file to multiple sections from the UI
#204 Edit metadata for a file that's attached to multiple sections
#205 Delete a file that's attached to multiple sections

**Comment by conorom** [comment]
Now that a FileSet's section(s) are simply stored as multi-valued fields (`section_title`) there is no issue with deleting such assets. No "clone" relationship exists.
