### ISSUE TITLE
Create an external resource (as an Editor)

### ISSUE THREAD

**Issue by shanitajohn** [mlibrary/heliotrope#219]
**STORY**
As an editor I want to be able to enter links to external resources so that I can create monographs that refer users to content outside the platform. 

**ACCEPTANCE** 
- [x] I can store a URL as part of an asset 
- [x] I can click on a URL to the external resource 

**NOTE** 
It's possible that we can repurpose the "attach a file" button, ie., change to "create an asset."

**Comment by val99erie** [comment]
You might be able to just add a property to the FileSet model to hold the URL(s).  Here's exmaple code of adding a new property:
https://github.com/curationexperts/heliotrope/commit/b53667a7

**Comment by sethaj** [comment]
In a follow-up email, Valerie talks about some different strategies for doing this. In worthwhile (depreciated, so we'd need to tweak it) they create a separate Fedora object:

[https://github.com/projecthydra-deprecated/worthwhile/blob/master/worthwhile-models/app/models/worthwhile/linked_resource.rb](https://github.com/projecthydra-deprecated/worthwhile/blob/master/worthwhile-models/app/models/worthwhile/linked_resource.rb)


Or we could just add the field to the FileSet model, maybe using the DC.source predicate, which would be simpler and more immediate.

Mark sent an email alluding to some PCDM guidelines for doing this which would could follow:

```
External Content
When binary data is served by another application, it may be appropriate to create a File object with no content to model the external content, hold related technical metadata, etc. Fedora 4's external content feature is one way to implement this link to the external content.

- from https://github.com/duraspace/pcdm/wiki
```

However we decide to handle this, we don't need to for summer beta 1 since the publication doesn't have these.

**Comment by sethaj** [comment]
@conorom has added an external_resource to FileSets as DC.source in PR #245, https://github.com/mlibrary/heliotrope/pull/245 but we still need to decide how these should look to end users (the "X box/no image" image probably isn't right).

**Comment by conorom** [comment]
For now we're trying out FileSets with a placeholder image, thus skipping around changes to the monograph page, minimizing changes to the FileSet page and allowing the flexibility of varied icons/placeholder images. We could have one per resource type, or even allow partners to provide, for example, a video freeze frame to use as the linked image to an externally-hosted video.
