### ISSUE TITLE
Work out Beta 1 Release details with A&E

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#248]
Need agenda items for meeting that is scheduled for July 5, 2016

Getting external partners access to preview (#250)

**Comment by jgmorse** [comment]
Query sent to Sebastien to see who should attend.

**Comment by jgmorse** [comment]
Meeting scheduled with A&E for July 5.

**Comment by jmcglone** [comment]
1. For external partner preview, we will make the testing/staging version publicly available but not share the URL widely and prevent indexers from crawling the site.
2. For Auth, we're using the Hydra way until this becomes problematic.
3. In staging, we are currently using the same repo as DBD. When we blow our own content away, we should be careful to include our content's top-level-domain to ensure that we are only destroying our own content (not DBD's). This will/should be identical in production.
4. Setting up redirects are not a problem for A&E. Aaron Elkiss is assuming the final pointer will be fulcrum.org/northwestern until he hears otherwise.
5. We can do anything you can usually do with Apache in the Puma/Apache setup.
6. sunny-d = dev // nectar = staging/test // bulleit-1 = production 
7. We *should* be able to continue using our existing cap deploy, but specify production and point to the production server. If anything requires work, it is a bug and A&E should fix it. Deployment to production should be tested before we deploy on Aug. 17.
