### ISSUE TITLE
Section facet order should match the set order of sections

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#276]
On the monograph catalog page, the Section facet order should reflect the set order of facets in the monograph. Currently, the facet order is set by:

1) the number of assets associated with a section and
2) alphabetically, by section name

The facet order should ignore these rules and be ordered by the section's set order in the monograph. 

An example of current and undesired behavior in the Section facets:

![screen shot 2016-06-28 at 4 20 22 pm](https://cloud.githubusercontent.com/assets/1686111/16430985/51f1c8d2-3d4c-11e6-9fdd-2981fbddcf76.png)

The true order of the sections as reflected in the Monograph show/manage Monograph page:

![screen shot 2016-06-28 at 4 20 59 pm](https://cloud.githubusercontent.com/assets/1686111/16431002/70c92548-3d4c-11e6-83fd-62ca58510c3a.png)

The Section facets should reflect this order.

**Comment by sethaj** [comment]
Right now the section facet sorts by number of assets in a section, which is the default for facets generally.

![section_facet_sort](https://cloud.githubusercontent.com/assets/3924142/16453914/931c82bc-3ddc-11e6-9982-5bbf5a0cdf23.png)

We can change this to facet section in order, but what happens if there's a monograph with 20 sections? Do we remove the limit on the section facet (it's currently limited to 5) and just display them all? If we don't, then we might end up displaying the first 5 (or whatever) sections, but later sections that we're not including in the facet have a lot of assets/files that users won't ever see.

Maybe that's ok, just wanted to bring it up.
