### ISSUE TITLE
Asterisk in copy should be used like for footnote

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#325]
In the description, if there is an asterisk in the copy, it stays displaying as an asterisk and does not display as a bullet point.

Should not look like: 

<img width="548" alt="asterisk2" src="https://cloud.githubusercontent.com/assets/17436011/17297041/ecd9c986-57d1-11e6-8dcc-188a22899b7a.png">

The metadata template looks like this:

<img width="248" alt="asterisk" src="https://cloud.githubusercontent.com/assets/17436011/17297055/00b39626-57d2-11e6-94a8-7fbca179333f.png">

**Comment by jmcglone** [comment]
Another way to phrase this -- support for footnotes in Asset descriptions. We need to find a recommended way to indicate footnotes using markdown that does not use existing Markdown characters. Since we can't change how Markdown interprets an asterisk and a space (it will always render as a bulleted list item), one way we could do footnotes would be to replace the asterisk with bracketed numbers that correspond to each other, something like the following:

...and use of the unexpected [1]. See book: frontispiece; p. 15, 16, 17, figure 5.

[1] Laurence Sterne, _The Life and Opinions of Tristram Shandy, Gentleman_, (Ware, U.K.: Wordsworth Editions, 1996)...

**Comment by conorom** [comment]
Looking at the [redcarpet readme](https://github.com/vmg/redcarpet), would the actual footnote option be preferred (where it should link as well), or just a superscript for the reference?

Or have we already decided to just delete the spaces after the asterisks in the metadata template?

**Comment by conorom** [comment]
I've turned superscript/footnotes on in a branch and experimented. They both work. Footnotes look nice, but the cute little backarrow gets weirdly bumped up to the top instead of following the footnote. It's not obvious to me why that happens. If we like the way the footnote looks enough then we/Jon can pursue what devious style is making that hop up there ;-) 

![screen shot 2016-08-09 at 1 45 54 pm](https://cloud.githubusercontent.com/assets/9595080/17529562/ca48ded6-5e41-11e6-9da6-a4280f3b38dd.png)
