### ISSUE TITLE
Fix thumbnails that are distorted on the monograph page

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#367]
Problem:

There are three assets that are displaying weird/distorted thumbnails on the Northwestern monograph page.

When you go to the asset's page, the asset displays properly.

The titles of the assets impacted are:
1. Costume design for the dance master, Columbine's Veil (29-Figure10...)
2. Scene design for The Green Bird (105-Figure34...)
3. Sketch of Columbine strangling Pierrot, Columbine's Veil (file 127-RGALI....)

Here is an example:
<img width="621" alt="screen shot 2016-08-05 at 6 15 25 pm" src="https://cloud.githubusercontent.com/assets/17436011/17522495/414580c4-5e25-11e6-8035-829ea5aafb6f.png">

**Comment by jmcglone** [comment]
Wow, this is really strange. May have something to do with how the derivs are getting created. Screenshots from heliotrope-testing for clarification:

![screen shot 2016-08-09 at 11 33 09 am](https://cloud.githubusercontent.com/assets/1686111/17522447/15d6b8c2-5e25-11e6-9ebd-72f5760ed735.png)

![screen shot 2016-08-09 at 11 33 43 am](https://cloud.githubusercontent.com/assets/1686111/17522461/267bdeaa-5e25-11e6-8b52-70bbbd5cf6dd.png)

![screen shot 2016-08-09 at 11 34 09 am](https://cloud.githubusercontent.com/assets/1686111/17522478/361cfb82-5e25-11e6-851a-f2b8bb58eb42.png)

**Comment by conorom** [comment]
Issue was caused by a bug in libtiff 4.0.3, which unfortunately is the version included with Debian stable. Although several of the bugs listed for libtiff are probably related to this issue, the sample images in bug #786910 are particularly helpful:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786910
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=libtiff5;dist=unstable
another relevant link:
http://imagemagick.org/discourse-server/viewtopic.php?t=16526

A&E did not want to pull in a version of libtiff that has not been approved/backported into Debian stable.
For now, the workaround on nectar is to use a local Imagemagick (/l/local/ImageMagick/bin/convert) which uses a local libtiff 4.0.6 (/l/local/tiff-4.0.6). These are being included in the Resque pool service's PATH here:
/etc/systemd/system/resque-pool@heliotrope-staging.service.d/path.conf
