### ISSUE TITLE
Markdown should be stable in the monograph description

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#387]
When I go to the monograph page for The Director's Prism, the title is in the monograph description and is marked up to be in italics.

The italics does not show up consistently.

Per JMc: Looks like a bug caused by the JS that is shortening the description length.

<img width="315" alt="screen shot 2016-08-12 at 2 40 50 pm" src="https://cloud.githubusercontent.com/assets/17436011/17633820/5073beb0-609d-11e6-89e7-6755fd5c2879.png">

<img width="238" alt="screen shot 2016-08-12 at 2 44 30 pm" src="https://cloud.githubusercontent.com/assets/17436011/17633832/5c2053c2-609d-11e6-8b4a-2fff9acb43ea.png">

**Comment by jmcglone** [comment]
Currently: when JS is applied it shortens the description length on the monograph page to 500 characters and Markdown is not successfully rendered. When JS is not applied to shorten the description, Markdown is successfully applied.

Expected behavior: when JS is applied it shortens the description length to 500 characters, includes a "more" link that expands the description, and any Markdown in the description is successfully rendered on the page.

The JS that performs this function is contained in `app/assets/javascripts/short_monograph_description.js`
