### ISSUE TITLE
Display persistent ID field on asset page

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#479]
If a persistent ID exists, show it on the Asset page's "Info" tab.

- [x] add `:doi` to fileset model, assign predicate
- [x] add `:handle` to fileset model, assign predicate
- [x] ensure that the handle and doi are in web form
- [x] if a handle or doi exists for an asset, it displays in the info tab under the "Citable Link" label
- [ ] ? (maybe) handle or doi should be an anchor tag that can be copied (see Hathi/Fishwrapper) (make a new UX specific ticket for this)
- [x] alter share links to use handle or doi
- [x] remove `:identifier` from fileset model
- [x] deploy to staging, test what happens
- [x] on production, put NW handles into the handle field for NW titles
- [x] on production, replace content in External URL/DOI with "handle"
- [x] MBY - put handles into the metadata template "Persistent ID - Display on Platform" field and share with NW

**Comment by sethaj** [comment]
```# Set handles for a monograph's file_sets
Monograph.find('9p290937n').ordered_members.to_a.each {|s| s.ordered_members.to_a.each do |f| 
if f.file_set?
f.hdl = f.id
puts f.id
f.save!
end
end}```

**Comment by sethaj** [comment]
The way handle work currently is that a books will *by default* use it's NOID as it's handle. We can put file sets into production and they will immediately have a "citable link" displayed that uses the book's NOID for it's handle even if the handle hasn't actually been registered yet. We need to do this right now since we can't know the NOID of a file set that isn't in production, so we can't register a handle for it until it's already in production. So there will be a brief period where the file set will display a handle that doesn't yet work.

Right now, the NW and Minn books have handle in production, meaning their `hdl` field has an entry (see the script in the comment above for how this is done) and the `ext_url_doi_or_handle` field say 'Handle'.

I have a question about the "book needs handles?" field. For the NW book it was "yes", for the Minn book "no". But aren't we always going to give books handles? If that's true, can we just remove the :book_needs_handles predicate? I'm also confused about the :use_crossref_xml field. Are we duplicating these with :doi and :hdl? These are line 20-21 on the Metadata spreadsheet: https://docs.google.com/spreadsheets/d/1Xzod0SL-Dev1Bh5TklU0OuvSsQhErfG_huDP3dpLcPo/edit#gid=1353609401

**Comment by sethaj** [comment]
We talked a bit about the above comment and the different persistent url/doi/handle fields.  Right now the model for these is in flux and we'll be making changes to it based on real use cases. What we have right now works for what we have. Jeremy is going to create a card/story with a different use case for an upcoming Michigan book and we'll probably make some changes based on what that use case needs.
