### ISSUE TITLE
Test searching functionality

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#502]
Make sure that searching on asset titles on the monograph page and asset page produces expected results.

Test:

- [x] Northwestern
- [x] Minnesota

**Comment by mbakeryo** [comment]
When on Northwestern, sometimes when searching on a title that has markdown in the title, the search yields no result. For example, see Scapino and Captain Zerbino:

<img width="892" alt="searchwithoutunderscore" src="https://cloud.githubusercontent.com/assets/17436011/18843341/6a63779a-83e6-11e6-8806-97895e20e78b.png">

If I place underscores around the title in the search box and search again, I will get the correct result:

<img width="982" alt="searchwithunderscore" src="https://cloud.githubusercontent.com/assets/17436011/18843359/7d5c146a-83e6-11e6-9222-834d345a3c5f.png">


This doesn't happen all the time, though. For example, a search on Kapellmeister Kreisler in Insanity, which has markdown around it, will yield a correct result without having to put underscores around the search criteria:

<img width="1039" alt="kapellmeisterkreislerininsanity" src="https://cloud.githubusercontent.com/assets/17436011/18843436/fc0e454e-83e6-11e6-88df-937396741dc4.png">

**Comment by sethaj** [comment]
I can verify that the "Scapino and Captain Zerbino" example is a problem in preview (and staging). In dev, on my machine, it works. I think we need to reload the solr cores in staging/preview/production, which will reload the solr config files which were modified for https://github.com/mlibrary/heliotrope/pull/426 to fix these markdown searching issues. When that's done, we'll need to re-index.

The solr cores are due to be reloading based on this issue: https://github.com/mlibrary/heliotrope/issues/469

I'll remind Colin about it and see when he wants to reload the cores.

**Comment by sethaj** [comment]
We've reloaded the solr config on staging, preview and production so the " Scapino and Captain Zerbino" issue for Northwestern should be resolved. Since this is sort of a "blanket search problems" ticket I'll leave it open until the Minnesota book has been looked at.
