### ISSUE TITLE
Citable Link fallback: DOIs, then Handles

### ISSUE THREAD

**Issue by jgmorse** [mlibrary/heliotrope#566]
When viewing an asset and the asset has a DOI in the metadata, then that DOI should display as the 'Citable Link'.  If there is no DOI, then the auto-generated handle should display as the 'Citable Link'.

Modifies #479.

**Comment by jgmorse** [comment]
Each of the :handle and :doi fields should only contain PURLs that refer to this item's record in Fulcrum.  Any other PURL which resolves to this content (or another version of it) in a different context should be stored in a different field (:external_purl ?).

**Comment by gkostin1966** [comment]
A PURL is a Persistent Uniform Resource Locator. Functionally, a PURL is a URL. However, instead of pointing directly to the location of an Internet resource, a PURL points to an intermediate resolution service. The PURL resolution service associates the PURL with the actual URL and returns that URL to the client as a standard HTTP redirect. [DOI® System and Persistent URLs (PURLs)](https://www.doi.org/factsheets/DOI_PURL.html)

**Comment by gkostin1966** [comment]
Current behavior is to switch on the value of the 'ext_url_doi_or_handle' field.  Implementation of the doi_url method in file_set_presenter.rb is blocked pending a use case that has a DOI.  It is unclear if the statement: "Any other PURL which resolves to this content (or another version of it) in a different context should be stored in a different field (:external_purl ?)." has a use case.  It is unclear if there is a use case that would override the DOI when it exist with a handle.  It seems unnecessary to me to index the doi and hdl fields and have them be multivalued.

I recommend that we remove the 'ext_url_doi_or_handle' field and simply use the value of the 'doi' field if it exist, otherwise use the value of the 'hdl' field (which should be renamed to 'purl').

**Comment by sethaj** [comment]
Here are the DOIs for the michigan book.

https://doi.org/10.3998/fulcrum.4q77fr32b	concern/file_sets/4q77fr32b	
https://doi.org/10.3998/fulcrum.jw827b69n	concern/file_sets/jw827b69n	
https://doi.org/10.3998/fulcrum.jh343s28d	concern/file_sets/jh343s28d	
https://doi.org/10.3998/fulcrum.q811kj674	concern/file_sets/q811kj674	
https://doi.org/10.3998/fulcrum.1v53jw986	concern/file_sets/1v53jw986	
https://doi.org/10.3998/fulcrum.0c483j399	concern/file_sets/0c483j399	
https://doi.org/10.3998/fulcrum.4b29b598d	concern/file_sets/4b29b598d

**Comment by sethaj** [comment]
Since we now have DOIs as a use case, we can solve the basic premise of this story. The logic is:

If an asset has a DOI: 
   use the DOI as the citable_link

If an asset has no DOI, but has an explicit handle: 
   use the explicit handle as the citable_link

If an asset has no DOI and no explicit handle: 
  use a default handle based on the NOID as the citable_link.

I think that should be it for now. We can add an :external_purl option once we have a use case. We can clean up/change the various possible extra fields (:ext_url_doi_or_handle?) that come from the metadata template as it becomes more clear what's needed and what's not. That's kind of a big job since it touches the metadata template (and all the old metadata templates), the importer and heliotrope. I don't think we should make changes until we're really sure what we want.
