### ISSUE TITLE
Investigate CPU issues with Able Player

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#717]
In Chrome, we've seen the CPU spike when playing back video with the Able Player. Investigate to see if this is a more widespread issue:

- [x] Is this a known issue?
- [x] Does it affect other browsers?
- [x] Does it impact other Operating Systems?

**Comment by sethaj** [comment]
Now that AblePlayer is in preview, I'm not seeing a problem any more. MY CPU usage is a little elevated, but nothing near 100%. Everything looks fine on nectar.

Before I was seeing 100% CPU when playing videos in Chrome in my dev environment, but I'm not even seeing that anymore. Maybe it was caused by something else.

**Comment by jmcglone** [comment]
Closing, seems to be a local dev environment issue only at this point.
