### ISSUE TITLE
Do user authentication the way UMRDR does

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#729]
- [ ] If user has an active UM Cosign session, import their Cosign credentials.
- [ ] If a UM user (or Friend account holder) does not have an active session, they should have the means to sign in to Cosign from the Rails login screen.

Implement this the same way UMRDR does until we have a new authz system that might dictate doing it another way (especially for OpenID support, which we eventually want to do.)

**Comment by mbakeryo** [comment]
@jgmorse Any update on this? We said we'd check in on it in April. I know this isn't part of this sprint, but if you could give an update at next sprint planning (April 27), that'd be great. If this isn't you, also let me know. :)

**Comment by jgmorse** [comment]
As discussed on 4/19, for now, all authentication will be through cosign; external users will use Friend accounts.  (We may not even need external accounts until we have a new authz system anyway.)

**Comment by sethaj** [comment]
We should probably get started on this.
- [ ] Take a look at umrdr and see what we need to do to get this working: https://github.com/mlibrary/umrdr/blob/master/app/controllers/sessions_controller.rb
(older stuff is:
https://github.com/mlibrary/umrdr/commit/1a59203d2fc294272c513a2d6d089c1d950a1dc0
https://github.com/mlibrary/umrdr/commit/129135752961f2d8d35030e31283c9958528551c)
- [ ] Coordinate the release of this (do it on nectar first) with A&E. They'll need to do some apache stuff. 
- [ ] Figure out how this should work in dev (no apache)
- [ ] I don't think we'll need to re-write the `rake admin` task. While it's true that users for "production" (anything w/ apache in front of it) won't need passwords anymore since cosign will vouch for them, I imagine we'll still need this in dev. Probably?
