### ISSUE TITLE
Investigate removing sections from data model

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#731]
Make a branch and rip-out sections where:

- [ ] Sections are a piece of metadata on a FileSet
- [ ] What breaks?

Do we still need to handle #202?

**Comment by sethaj** [comment]
A lot of work has been done on this, mostly by Valerie. It's looks like we will go forward with this and will remove Sections from our data model.

We have a separate branch called `sections_as_metadata` which has much of the section code removed as well as a rake task to migrate the data. The migration process for staging/preview/production looks something like this:

1. Deploy `master`
2. `bundle install` (if needed)
3. (on master) `be rake heliotrope:reverse_upload_dates` if needed
4. Deploy `sections_as_metadata`
5. (on sections_as_metadata) `be rake heliotrope:sections_as_metadata`
6. Verify  (somehow)
7. If ok on staging/preview and production: merge sections_as_metadata to master
8. Deploy master


 Once `sections_to_metadata` is deployed, and the migration rake task is run, everything should be stable. Below are some notes from Valerie about things that may still need to be done, but these can be done after the `sections_to_metadata` branch have been deployed.

* app/views/curation_concerns/file_sets/show.html.erb
  Make sure the FileSet show page is working properly.
  I thought I saw that page broken, even though specs were green.
  But I'm not sure.

* Importer

* Fix or delete any specs that are marked 'skip'

* Convert everything in the UI so that setting/editing section title uses FileSet#section_title, not Section#title.

* Make sure we haven't messed up the google analytics
  See the note about ga_event_tracking in spec/features/monograph_catalog_search_spec.rb

* Do we need a spec to test that the section title appears correctly for entries on the monograph catalog page?
"From Chapter 2: Tairov-Celionati: Mime-Drama and Kaleidoscopic Commedia"

* On the monograph show page what do we want to display under "Sections"?
    -- section titles, but no links
    -- section titles with facet search links
    -- nothing; just remove that partial

  app/views/curation_concerns/monographs/_sections.html.erb
  spec/features/show_monograph_spec.rb

* unregister section in config/initializers/curation_concerns.rb 
    -- remove section code: app/models/search_builder.rb 
    -- remove section code: spec/models/search_builder_spec.rb

**Comment by sethaj** [comment]
This first (and most important) part of this is done. Sections have been removed and are now metadata in the FileSet in master which is deployed as tag 1.2 in staging/preview/production. 

Still need to clean up all the other bits as per Valerie's notes above.
