### ISSUE TITLE
Fix caption issue for Animal Acts

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#745]
- [x] At the 40:00:03:07 mark (Sit down, Carol) the time code displays.

Seems like audience response with >> with text from caption is throwing the text from showing

There are too many problems with the three solutions listed below.
These are the steps to close this ticket:
- [ ] turn off Able Player's interactive transcript
- [ ] display the WebVTT file in the transcript area in its entirety

**Comment by mbakeryo** [comment]
Upon investigation this issue (on staging on the video Everything I've Got), there are two problems:

Issue 1: While you can have multiple lines within one time cue, in the Transcripts section of the asset page, these lines are not separated by a break, only a hyphen.

<img width="300" alt="screen shot 2017-02-09 at 9 00 10 am" src="https://cloud.githubusercontent.com/assets/17436011/22787200/7b6ee80c-eea9-11e6-9a96-76c371d0822c.png">
<img width="542" alt="screen shot 2017-02-09 at 8 54 14 am" src="https://cloud.githubusercontent.com/assets/17436011/22787203/7dfd7e12-eea9-11e6-8f2d-aad7750cc751.png">

Issue 2: 
While you should be able to construct your WEBVTT files with sound effects by surrounding the sound with brackets, doing so will drop any additional lines within that cue.

<img width="327" alt="screen shot 2017-02-09 at 9 03 01 am" src="https://cloud.githubusercontent.com/assets/17436011/22787252/af756806-eea9-11e6-9fd4-af23d556293c.png">
<img width="367" alt="screen shot 2017-02-09 at 9 04 02 am" src="https://cloud.githubusercontent.com/assets/17436011/22787266/b3de9c82-eea9-11e6-8377-1aa0205e9609.png">

Is this potentially a problem with the stylesheet or something similar to what was causing the problem with the translations formatting not sticky when we were working on NU?

**Comment by conorom** [comment]
Something must be happening to the newlines etc, indicating rendering as html before the Able Player stuff kicks in. Try ` render plain:` instead of `render text:` and/or adding a content type of `text/plain` or `text/vtt`.
`render plain:` with `text/vtt` probably makes the most sense, assuming it works!
https://makandracards.com/makandra/25019-when-using-render-text-set-a-content-type

**Comment by conorom** [comment]
The above controller change makes no discernible difference. I guess we can set it to `plain:` because of the deprecation anyway.

The main issue is that Able Player's automatic transcript generation is coded to work to meet the developer's own  vision of WebVTT usage, and for us it falls short, particularly in relation to the exact items mentioned here:
- the parsing of brackets and parentheses
- honoring new lines within a cue

There is nothing wrong with what we're doing per se, e.g. having non-verbal noises within a cue along with verbal (or other non-verbal) parts, like here:
https://svs.gsfc.nasa.gov/vis/a010000/a011800/a011895/11895_Fermi_Binary_Pulsar_SRT_Captions.en_US.vtt
...but Able player expects those to sit in a cue by themselves and discards anything coming after in the div-generating JS code.

Our choices boil down to:
1) making changes in our WebVTT files. Quite a bit of hoop-jumping where brackets are used, and in the following cue, too, where I think Able Player's transcript generator expects the next voice to be introduced at the start of the next cue (see image). Then (assuming new lines in cues are important we enable data-lyrics-mode as in this example:
https://ableplayer.github.io/ableplayer/demos/audio4.html
https://ableplayer.github.io/ableplayer/media/paulallen_en.vtt

![image](https://cloud.githubusercontent.com/assets/9595080/22896627/db58e09a-f1ee-11e6-9077-999f59d3bf5d.png)


2) hacking/forking or contributing to Able Player to do automatic transcript generation the way we want. In particular we want to remove the assumption that a non-verbal part always sits on its own here:
https://github.com/ableplayer/ableplayer/blob/develop/scripts/transcript.js

3) Jump through hoops the way Able Player recommends. Probably start off with an automatic transcription and edit the generated div (as suggested). We end up writing the HTML for the transcript, as in this example:
https://ableplayer.github.io/ableplayer/demos/video7.html

**Comment by mbakeryo** [comment]
In looking at Staging, the transcript box on the asset page looks good - there is no interactive functionality, therefore, no text has been dropped. 

However, on the viewer, there is now a Transcript button and when selected, the transcript pops up beside the viewer and it is the interactive version of the transcript. 

As this version of the transcript is incorrect (truncated, etc.) can that Transcript button be deactivated? (FWIW, that button does not appear currently on the Fulcrum.org production site.)
