### ISSUE TITLE
Update metadata template BP/P field

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#807]
- [x] Not required
- [ ] Exclusive for Fulcrum - yes = true, empty and no = false

**Comment by mbakeryo** [comment]
3/20/17: Create new metadata template version with changes: https://docs.google.com/spreadsheets/d/1l_rYvIuBGLBBQ7YdY_mymuug0bVgwBeYBUGP66n4jvI/edit#gid=1726739743

Things to note:

--Changed the field so it is no longer required.
--Changed the field label (on the template) from Book and Platform (BP) or Platform-only (P) to Exclusive to Fulcrum. 
--Changed the location of the field since it’s no longer required (took from required grouping and placed before persistent id column)
--Changed the options to Yes or No
--Changed instructions to say: 
This field is to highlight if the digital asset only appears on Fulcrum. If 
Yes is selected, the asset will be flagged as exclusive and will be identified as Exclusive to Fulcrum in the Exclusivity facet. 

Select Yes if the digital asset will only appear on Fulcrum.

Select No if the digital asset will appear somewhere else, e.g., in the 
print book or ebook.
	
Select No if the digital asset is an externally hosted resource.
