### ISSUE TITLE
Add "Site Requires Cookies Enabled" message for users

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#811]
This is a safeguard for the bug identified in #809 - when users have cookies disabled, the user is not redirected to the asset page. This is a blacklight problem that can be fixed if we disable tracking, however it isn't clear if we want to do that.

- [ ] detect if cookies are enabled by setting a cookie and then checking for it
- [ ] if cookies are not enabled, display a warning message across the top or bottom of the browser
- [ ] when closed by the user, it registers another cookie so that the message is no longer displayed. (of course this will only work if they have since enabled cookies)
- [ ] if cookies continue to be disabled and the message is close this message will continue to appear until the user enables cookies.

**Comment by sethaj** [comment]
The PR for this is mostly right. It's a little different than above:

* If you have cookies disabled, you'll get the "The site requires cookies to function correctly" message.
* The message will follow you all over the site (unless you get to a page, see #809, that gives you an error, more on that below)
* If you click the X on the message (close it), it will go away and the page will be reloaded.
* If you still have cookies disabled, the message will reappear.
* In order to get the message to go away, you need to enable cookies and then click the X. The page will be reloaded and the message will be gone.

We need to reload the page because the problem described in #809 ends up with a ActionController::InvalidAuthenticityToken error. In order to get the token, you need to load the page with cookies enabled. You can't just enable them on a page, click and link, and have it work.

Also, this message does not appear on actual error pages. It looks like those aren't working right and are actually just empty responses with no html. Need create a new issue/story for that.
