### ISSUE TITLE
Add draft mode for monographs

### ISSUE THREAD

**Issue by mbakeryo** [mlibrary/heliotrope#839]
As a publisher admin, I can set a monograph as a DRAFT and it won't be public, but other Pub admins AND Platform admins can see and edit it.

**Comment by mbakeryo** [comment]
Check on how this relates to Hyrax

**Comment by sethaj** [comment]
It doesn't seem like Hyrax offers anything new for this, but there's quite a bit of existing infrastructure in bliacklight, hydra and hyrax. There's a nice breakdown of these complex permission interactions by LaRita from Notre Dame here:

https://docs.google.com/document/d/1tWpV8b11WZ5qXP0ZHgFtatVuRg3YFUoMA7jPzU-QB34/edit
 
DBD is using the Private visibility as "Draft". We could do that too. But the fact that we have Presses/Publishers really changes things. For instance, a user isn't an "admin" but is an admin for a specific Press (or can have multiple roles in multiple presses). This makes access to Draft(Private) Monoraphs/Assets more complex.

It seems like the best way is to explicitly assign a role to Work/FileSet (Object). This functionaliy seems supported by the various gems (blacklight-access-controls, hydra-access-controls, parts of hyrax). Normally one would add the role/group to the Object for instance allowing "read" and "edit" to both the admin role and the editor role:

```
monograph.edit_groups =  ['admin', 'editor']
monograph.read_groups = ['admin, 'editor']
monograph.save!
```

The doesn't work for us because we need a Press/Publisher context for each Object and role. I've tried different ways to do this, but it seems like the simplist way (instead of trying to divine the Press context of each request from "all kinds of stuff") is just to explicitly add the press to the role by merging the Press.subdomain and Role on each Object permission. So we'd have:

```
monograph.edit_groups  = ["michigan_admin", "michigan_editor"]
monograph.read_groups = ["michigan_admin", "michigan_editor"]
monograph.save!
```

We can keep our current Roles the same (right now just "editor" and "admin") but then merge the User to the Role based on their Press on the fly to get access permissions. But in the Object the "subdomain_role" would be hard coded and persisted (in fedora and solr).

This *could* get out of hand if an Object has a lot of roles across many Presses, but when would that actually happen (not often or ever probably)? 

Still need to experiment and write tests, but there's a branch with this approach, "draft_mode_3".
