### ISSUE TITLE
Upload epub like an asset

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#871]
- [x] An epub media in heliotrope publisher
- [x] Make additional cards for what comes next
#889 EPub should not appear in asset list.
#890 Has EPub Indication?

**Comment by sethaj** [comment]
What exactly happens when we upload an epub to a Monograph as a FileSet? I don't think a derivative gets made.... FITS probably doesn't run. The app won't really know about it's "epubness", but it will likely need to be aware of it.

So for the next card in this series, maybe add a new field to the Monograph (and all that entails (https://github.com/projecthydra/sufia/wiki/Customizing-Metadata) that behaves like representative_media but for the epub so that a user can assign the epub asset/file_set to the Monograph? Should the FIleSet itself be aware of it's own "epubness" (might not need that since we can use mime-type)?

**Comment by gkostin1966** [comment]
EPub on staging: https://heliotrope-staging.hydra.lib.umich.edu/concern/file_sets/hm50tr89c
