### ISSUE TITLE
Improve deployment of cozy-sun-bear

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#968]
To reduce the need manually update to `Gemfile` by tracking a commit when deploying updates to CSB, we'll need to:

- [x] on [cozy-sun-bear](https://github.com/mlibrary/cozy-sun-bear), create a `release` branch
- [ ] modify `Gemfile` to point to this `release` branch
- [ ] update cap deploy scripts to do `bundle update cozy-sun-bear ` before the `:compile_assets` call

**Comment by jmcglone** [comment]
Getting the bundle to execute at the right point has been a struggle, and alternative deployment methods are currently being discussed. In particular, the possibility of not checking in the `dist` files and explicitly running a build of the `dist` files in whatever project is using CSB.

**Comment by jmcglone** [comment]
This will probably be fixed by moving to Rails 5.1

**Comment by sethaj** [comment]
We've updated to Rails 5.1.3. Right now, nothing has changed with the way we add javascript to the app using the asset pipeline but we now have the option of using webpack + yarn instead. So we could do the work of investigating that and see if that will help us out. But I'm wondering: will using yarn and package.json and webpack really help us with this issue? We'd still need to update package.json (instead of Gemfile) with new CSB github refs. (Probably: need to investigate how that all works of course).

Maybe the right solution here is to (more) formalize CSB releases. Right now it's all pretty much `master` but couldn't CSB have more normal, or ideally even semantic versioned releases? And then we'd just update the heliotrope Gemfile with version numbers like we do with every other gem we use?

**Comment by jmcglone** [comment]
+1 to the idea that we need to formalize CSB releases, using semantic versioned releases. If others agree I can create a ticket in CSB and update the acceptance criteria in this ticket.
