### ISSUE TITLE
2-up case studies on homepage

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#982]
Change the layout of the case studies on the fulcrum homepage. Instead of showing one title per row, show two titles per row.

**Comment by mbakeryo** [comment]
Per Charles on 8/9/17: on Fulcrum homepage, say "Partners" and use logos.

**Comment by mbakeryo** [comment]
@jmcglone: I wonder what your thoughts are. Should we change this ticket so that it says to use partner heading and display logos, or should we leave this one and create a new one for the partner/partner logos....I didn't get a sense of urgency on this, did you? Or, not to overload your usability testing, but maybe we delete this ticket and wait until that testing reveals the navigation needs?

**Comment by mbakeryo** [comment]
Deciding to delete this ticket. Will wait to get feedback from usability survey. If Charles indicates before then that he wants the homepage updated, we'll make a new ticket.
