### ISSUE TITLE
Investigate db:seed rake task

### ISSUE THREAD

**Issue by jmcglone** [mlibrary/heliotrope#986]
When running `bundle exec rake db:seed` to add a new press, the press is not created despite output saying the press was created/updated.

- [x] Investigate to figure out what (validations?) are preventing the creation. 
- [x] Add validations to the rake task and its output so you know the press was not created because of a validation error

**Comment by conorom** [comment]
The validations preventing the creation of the new presses were on `google_analytics` (where applicable) and 'logo_path'.  I reckon I added these validations simply because of the asterisk in the wireframe. Perhaps that was just indicating browser validation, though.
Maybe we don't need *any* validations on these. We have fall-back code for the logo anyway and could be that not every press uses Google Analytics.

It's worth noting that, even without a specific validation of presence, logo_path is being monitored by CarrierWave and so needs to be a file that actually exists.

This type of thing seems to work if the file is there, this is the only way I can get this set in dev using `seeds.rb`:
`press.logo_path = Rails.root.join("app/assets/images/press_image.png").open`

Weirdly, in staging/preview it was happy to write the row and just leave this field blank when attempting to set it to a string. Guess it's production vs dev behavior.

set local file in `seeds.rb`:
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-%22Upload%22-from-a-local-file

set remote file in `seeds.rb`
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Upload-remote-image-urls-to-your-seedfile

I think ticket #980 needs to be done before the validation part of this one is finished.

**Comment by jmcglone** [comment]
After testing the form I realize the Google Analytics field should not be a required field -- example use case: we just want to setup a test/dummy press (like Heliotrope) and don't want to have to put a GA id there OR a press doesn't have or want its own GA account.

**Comment by gkostin1966** [comment]
Created a publishers.yml file inside the db directory and output success or failure based on the return value of save (puts "#{press.errors.messages.inspect}" on failure).
